apiVersion: v1
kind: Service
metadata:
  name: {{ include "goldengate.fullname" . }}
  labels:
    app: goldengate
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: https
      port: {{ .Values.service.securePort }}
      targetPort: {{ .Values.service.securePort }}
  selector:
    app: goldengate
  type: {{ .Values.service.type }}